from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')

src += Glob('clock/*.c')
src += Glob('timer/*.c')
src += Glob('uart/*.c')
src += Glob('rtc/*.c')
src += Glob('gpio/*.c')


if GetDepend(['BSP_USING_I2C']):
    src += Glob('i2c/*.c')

if GetDepend(['BSP_USING_SPI']):
    src += Glob('spi/*.c')

if GetDepend(['RT_USING_SDIO']):
    src += Glob('sdio/*.c')

if GetDepend(['BSP_USING_USB_DEVICE']):
    src += Glob('usb/device/*.c')
    src += Glob('usb/phy/*.c')

if GetDepend(['RT_USING_ENET1']):
    src += Glob('net/*.c')

list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
